stages:
  - build

image: docker:19.03.12

services:
  - docker:19.03.12-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal
  LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker pull $LATEST_IMAGE || true
    - docker build --pull --tag $LATEST_IMAGE --build-arg=CI_PROJECT_DIR=$CI_PROJECT_DIR --build-arg=CI_PROJECT_URL=$CI_PROJECT_URL .
    - docker push $LATEST_IMAGE

#  vim: set ts=2 sw=2 tw=0 et :
